### ISSUE TITLE
TypeError: 'tuple'

### ISSUE THREAD

**Issue by rjp109** [paulbrodersen/somnotate#16]
When trying to run the '05_manual_refinement.py' script, the gui does not seems to work properly and almost every one of the keys i press (except 'w', 'n' ,and 'r' for state changes) results in the error below. I think this might  be due to the version of matplotlib that i am using. Generally, it would be useful to get a list of the exact versions of all your dependencies if possible. 

`Traceback (most recent call last):
  File "C:\Users\rp17047\AppData\Local\miniconda3\envs\somnotate_env\lib\site-packages\matplotlib\cbook.py", line 298, in process
    func(*args, **kwargs)
  File "C:\Users\rp17047\somnotate\somnotate\_manual_state_annotation.py", line 829, in _on_motion
    super(TimeSeriesStateAnnotator, self)._on_motion(event)
  File "C:\Users\rp17047\somnotate\somnotate\_manual_state_annotation.py", line 274, in _on_motion
    self._handle_hold_click(event)
  File "C:\Users\rp17047\somnotate\somnotate\_manual_state_annotation.py", line 264, in _handle_hold_click
    self._update_selection(*sorted([self.button_press_start, event.xdata]))
  File "C:\Users\rp17047\somnotate\somnotate\_manual_state_annotation.py", line 600, in _update_selection
    vertices[[0, 1, -1], 0] = selection_lower_bound
TypeError: 'tuple' object does not support item assignment`

**Comment by paulbrodersen** [comment]
This issue should be resolved in the latest commit. The problem arose from a recent change in matplotlib's API, specifically in Axvspan's  `get_xy` and `set_xy` methods, which used to return/set all vertices of the corresponding rectangle but now only apply to its origin.

**Comment by paulbrodersen** [comment]
Feel free to re-open if the issue persists.
